version: "3.8"

services:

  user-service:
    build:
      context: ..
      dockerfile: submission/user-service/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - micro-network

  product-service:
    build:
      context: ..
      dockerfile: submission/product-service/Dockerfile
    ports:
      - "3001:3001"
    networks:
      - micro-network

  gateway-service:
    build:
      context: ..
      dockerfile: submission/gateway-service/Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge